import base64
DQ = chr(34)
BS = chr(92)
DDQ = DQ+DQ
EM = chr(8212)
def q(s): return DDQ+s+DDQ
M = []
M.append("        /// <summary>")
M.append("        /// Generates a synchronized Canvas animation with mass-spring-damper,")
M.append("        /// phasor spiral, and sinusoidal waveform "+EM+" all driven by requestAnimationFrame.")
M.append("        /// Parameters: xi1, xi2 (damping ratios), label1, label2, title, wn")
M.append("        /// </summary>")
M.append("        private string GenerateSpringAnimation(int w, int h, Dictionary<string, string> p)")
M.append("        {")
M.append("            var title = p.GetValueOrDefault("+DQ+"title"+DQ+", "+DQ+"Animacion Sincronizada"+DQ+");")
M.append("            var xi1 = p.GetValueOrDefault("+DQ+"xi1"+DQ+", p.GetValueOrDefault("+DQ+"xi"+DQ+", "+DQ+"0.125"+DQ+"));")
M.append("            var xi2 = p.GetValueOrDefault("+DQ+"xi2"+DQ+", "+DQ+"0.5"+DQ+");")
M.append("            var label1 = p.GetValueOrDefault("+DQ+"label1"+DQ+", "+DQ+"poco amortiguamiento"+DQ+");")
M.append("            var label2 = p.GetValueOrDefault("+DQ+"label2"+DQ+", "+DQ+"buen amortiguamiento"+DQ+");")
M.append("            var wnVal = p.GetValueOrDefault("+DQ+"wn"+DQ+", "+DQ+"2"+DQ+");")
M.append("")
M.append("            // Unique ID to avoid collisions when multiple animations coexist")
M.append("            var uid = "+DQ+"sa"+DQ+" + Guid.NewGuid().ToString("+DQ+"N"+DQ+").Substring(0, 8);")
M.append("")
M.append("            // Escape strings for safe JS embedding")
M.append("            string JsEsc(string s) => s.Replace("+DQ+BS+BS+DQ+", "+DQ+BS+BS+BS+BS+DQ+").Replace("+DQ+BS+DQ+DQ+", "+DQ+BS+BS+BS+DQ+DQ+").Replace("+DQ+BS+"n"+DQ+", "+DQ+" "+DQ+").Replace("+DQ+BS+"r"+DQ+", "+DQ+DQ+");")
M.append("")
M.append("            var sb = new StringBuilder();")
M.append("")
M.append("            // Canvas element")
M.append("            sb.Append("+DQ+"<canvas id="+BS+DQ+DQ+").Append(uid)")
M.append("              .Append("+DQ+BS+DQ+" width="+BS+DQ+"880"+BS+DQ+" height="+BS+DQ+"480"+BS+DQ+" style="+BS+DQ+"border:2px solid #ddd;border-radius:8px;background:#fafafa;display:block;margin:10px auto"+BS+DQ+"></canvas>"+DQ+");")
M.append("")
M.append("            // Speed slider controls")
M.append("            sb.Append("+DQ+"<div style="+BS+DQ+"text-align:center;margin:6px auto;font-size:12px;color:#555;font-family:sans-serif"+BS+DQ+">"+DQ+");")
M.append("            sb.Append("+DQ+"<label>&#9654; Velocidad: <input type="+BS+DQ+"range"+BS+DQ+" id="+BS+DQ+DQ+").Append(uid).Append("+DQ+"spd"+BS+DQ+" min="+BS+DQ+"0.1"+BS+DQ+" max="+BS+DQ+"3.0"+BS+DQ+" step="+BS+DQ+"0.1"+BS+DQ+" value="+BS+DQ+"0.6"+BS+DQ+" style="+BS+DQ+"width:200px;vertical-align:middle"+BS+DQ+"> "+DQ+");")
M.append("            sb.Append("+DQ+"<b><span id="+BS+DQ+DQ+").Append(uid).Append("+DQ+"sv"+BS+DQ+">0.6</span>x</b></label>"+DQ+");")
M.append("            sb.Append("+DQ+"&nbsp;&nbsp;<button id="+BS+DQ+DQ+").Append(uid).Append("+DQ+"rst"+BS+DQ+" style="+BS+DQ+"font-size:11px;padding:2px 8px;cursor:pointer"+BS+DQ+">Reset</button>"+DQ+");")
M.append("            sb.Append("+DQ+"</div>"+DQ+");")
M.append("")
M.append("            // Build JS "+EM+" ported from sync_anim$ macro (anim_lib.cpd)")
M.append("            var js = @"+DQ+"(function(){")
M.append("var cv=document.getElementById("+q("__UID__")+");if(!cv)return;")
M.append("var c=cv.getContext("+q("2d")+"),W=880,H=480;")
M.append("var wn=__WN__,tMax=25,nP=500,prog=0,spd=0.6,pF=0;")
M.append("var x1v=__XI1__,x2v=__XI2__,c1="+q("#d32f2f")+",c2="+q("#1565c0")+";")
M.append("var sl=document.getElementById("+q("__UID__spd")+"),sv=document.getElementById("+q("__UID__sv")+"),rb=document.getElementById("+q("__UID__rst")+");")
M.append("if(sl){sl.addEventListener("+q("input")+",function(){spd=parseFloat(this.value);sv.textContent=spd.toFixed(1);});}")
M.append("if(rb){rb.addEventListener("+q("click")+",function(){spd=0.6;sl.value=0.6;sv.textContent="+q("0.6")+";prog=0;pF=0;});}")
M.append("var msH=185,eq=115,amp=35,pcx=135,pcy=340,pR=120;")
M.append("var wL=295,wR=865,wT=220,wB=460,wW=wR-wL,wH=wB-wT,wCY=wT+wH/2;")
M.append("function rsp(t,xi){var w=wn*Math.sqrt(1-xi*xi);return Math.exp(-xi*wn*t)*Math.sin(w*t);}")
M.append("function env(t,xi){return Math.exp(-xi*wn*t);}")
M.append("function pXf(t,xi){var w=wn*Math.sqrt(1-xi*xi);return Math.exp(-xi*wn*t)*Math.cos(w*t);}")
M.append("function tXf(t){return wL+(t/tMax)*wW;}")
M.append("function vYf(v){return wCY-v*(wH/2);}")
M.append("function zig(x,y1,y2,n){")
M.append("  var s=(y2-y1)/(2*n+2);c.beginPath();c.moveTo(x,y1);c.lineTo(x,y1+s);")
M.append("  for(var i=0;i<n;i++){c.lineTo(x-10,y1+s*(2*i+2));c.lineTo(x+10,y1+s*(2*i+3));}")
M.append("  c.lineTo(x,y2);c.strokeStyle="+q("#777")+";c.lineWidth=1.5;c.stroke();")
M.append("}")
M.append("function pis(x,y1,y2){")
M.append("  var m=(y1+y2)/2,pw=7,ph=14;c.strokeStyle="+q("#aaa")+";c.lineWidth=1.5;")
M.append("  c.beginPath();c.moveTo(x,y1);c.lineTo(x,m-ph/2);c.stroke();")
M.append("  c.strokeRect(x-pw,m-ph/2,pw*2,ph);")
M.append("  c.beginPath();c.moveTo(x,m+ph/2);c.lineTo(x,y2);c.stroke();")
M.append("}")
M.append("function bx(x,y,w,h,col,txt){")
M.append("  c.fillStyle=col;c.fillRect(x,y,w,h);c.fillStyle="+q("#fff")+";")
M.append("  c.font="+q("bold 13px sans-serif")+";c.textAlign="+q("center")+";c.fillText(txt,x+w/2,y+h/2+5);")
M.append("}")
M.append("function drawMS(tCur){")
M.append("  var a1=amp*rsp(tCur,x1v),a2=amp*rsp(tCur,x2v);")
M.append("  c.fillStyle="+q("#333")+";c.font="+q("bold 12px sans-serif")+";c.textAlign="+q("center")+";")
M.append("  c.fillText("+q("__TITLE__")+",W/2,16);")
M.append("  var px1=290;")
M.append("  c.fillStyle=c1;c.font="+q("bold 10px sans-serif")+";")
M.append("  c.fillText("+DDQ+BS+"u03BE = "+DDQ+"+x1v+"+DDQ+" (__LAB1__)"+DDQ+",px1,33);")
M.append("  c.fillStyle="+q("#666")+";c.fillRect(px1-50,40,100,5);")
M.append("  for(var i=0;i<5;i++)c.fillRect(px1-45+i*20,35,2,5);")
M.append("  zig(px1-18,45,eq+a1,5);pis(px1+18,45,eq+a1);bx(px1-22,eq+a1,44,32,c1,"+q("m")+");")
M.append("  var px2=590;")
M.append("  c.fillStyle=c2;c.font="+q("bold 10px sans-serif")+";")
M.append("  c.fillText("+DDQ+BS+"u03BE = "+DDQ+"+x2v+"+DDQ+" (__LAB2__)"+DDQ+",px2,33);")
M.append("  c.fillStyle="+q("#666")+";c.fillRect(px2-50,40,100,5);")
M.append("  for(var i=0;i<5;i++)c.fillRect(px2-45+i*20,35,2,5);")
M.append("  zig(px2-18,45,eq+a2,5);pis(px2+18,45,eq+a2);bx(px2-22,eq+a2,44,32,c2,"+q("m")+");")
M.append("  c.setLineDash([3,3]);c.strokeStyle="+q("#bbb")+";c.lineWidth=0.5;")
M.append("  c.beginPath();c.moveTo(200,eq+16);c.lineTo(700,eq+16);c.stroke();c.setLineDash([]);")
M.append("  c.fillStyle="+q("#aaa")+";c.font="+q("8px sans-serif")+";c.textAlign="+q("left")+";c.fillText("+q("equilibrio")+",205,eq+14);")
M.append("  if(Math.abs(a1)>2){c.strokeStyle=c1;c.lineWidth=1;")
M.append("    c.beginPath();c.moveTo(px1+28,eq+16);c.lineTo(px1+28,eq+a1+16);c.stroke();")
M.append("    c.beginPath();c.moveTo(px1+25,eq+a1+16);c.lineTo(px1+28,eq+a1+10);c.stroke();")
M.append("    c.beginPath();c.moveTo(px1+31,eq+a1+16);c.lineTo(px1+28,eq+a1+10);c.stroke();}")
M.append("  if(Math.abs(a2)>2){c.strokeStyle=c2;c.lineWidth=1;")
M.append("    c.beginPath();c.moveTo(px2+28,eq+16);c.lineTo(px2+28,eq+a2+16);c.stroke();")
M.append("    c.beginPath();c.moveTo(px2+25,eq+a2+16);c.lineTo(px2+28,eq+a2+10);c.stroke();")
M.append("    c.beginPath();c.moveTo(px2+31,eq+a2+16);c.lineTo(px2+28,eq+a2+10);c.stroke();}")
M.append("  c.textAlign="+q("center")+";c.font="+q("11px sans-serif")+";")
M.append("  c.fillStyle=c1;c.fillText("+DDQ+BS+"u2195 Vibra MUCHO"+DDQ+",px1,msH-5);")
M.append("  c.fillStyle=c2;c.fillText("+DDQ+BS+"u2195 Vibra poco"+DDQ+",px2,msH-5);")
M.append("}")
M.append("function drawPH(n){")
M.append("  c.fillStyle="+q("#333")+";c.font="+q("bold 11px sans-serif")+";c.textAlign="+q("center")+";")
M.append("  c.fillText("+q("Diagrama Fasorial (espiral)")+",pcx,205);")
M.append("  c.setLineDash([3,3]);c.strokeStyle="+q("#ddd")+";c.lineWidth=1;")
M.append("  c.beginPath();c.arc(pcx,pcy,pR,0,2*Math.PI);c.stroke();")
M.append("  c.beginPath();c.arc(pcx,pcy,pR*0.5,0,2*Math.PI);c.stroke();")
M.append("  c.setLineDash([]);c.strokeStyle="+q("#ddd")+";c.lineWidth=0.5;")
M.append("  c.beginPath();c.moveTo(pcx-pR-10,pcy);c.lineTo(pcx+pR+10,pcy);c.stroke();")
M.append("  c.beginPath();c.moveTo(pcx,pcy-pR-10);c.lineTo(pcx,pcy+pR+10);c.stroke();")
M.append("  drawSp(x1v,c1,n);drawSp(x2v,c2,n);")
M.append("  c.fillStyle="+q("#999")+";c.font="+q("9px sans-serif")+";c.textAlign="+q("center")+";")
M.append("  c.fillText("+q("El vector gira y decrece")+",pcx,H-8);")
M.append("}")
M.append("function drawSp(xi,col,n){")
M.append("  c.strokeStyle=col;c.lineWidth=1.5;c.globalAlpha=0.5;c.beginPath();")
M.append("  for(var i=0;i<=n;i++){var t=i*tMax/nP,px=pcx+pXf(t,xi)*pR,py=pcy-rsp(t,xi)*pR;")
M.append("    if(i===0)c.moveTo(px,py);else c.lineTo(px,py);}")
M.append("  c.stroke();c.globalAlpha=1;")
M.append("  if(n>0){var t2=n*tMax/nP,px2=pcx+pXf(t2,xi)*pR,py2=pcy-rsp(t2,xi)*pR;")
M.append("    c.fillStyle=col;c.beginPath();c.arc(px2,py2,4,0,2*Math.PI);c.fill();")
M.append("    c.strokeStyle=col;c.globalAlpha=0.3;c.lineWidth=1;")
M.append("    c.beginPath();c.moveTo(pcx,pcy);c.lineTo(px2,py2);c.stroke();c.globalAlpha=1;}")
M.append("}")
M.append("function drawWF(n){")
M.append("  c.fillStyle="+q("#333")+";c.font="+q("bold 11px sans-serif")+";c.textAlign="+q("center")+";")
M.append("  c.fillText("+q("Forma Sinusoidal x(t)")+",wL+wW/2,205);")
M.append("  c.strokeStyle="+q("#eee")+";c.lineWidth=0.5;var i;")
M.append("  for(i=0;i<=10;i++){var gx=wL+i*wW/10;c.beginPath();c.moveTo(gx,wT);c.lineTo(gx,wB);c.stroke();}")
M.append("  for(i=0;i<=8;i++){var gy=wT+i*wH/8;c.beginPath();c.moveTo(wL,gy);c.lineTo(wR,gy);c.stroke();}")
M.append("  c.strokeStyle="+q("#bbb")+";c.lineWidth=0.7;")
M.append("  c.beginPath();c.moveTo(wL,wCY);c.lineTo(wR,wCY);c.stroke();")
M.append("  c.strokeStyle="+q("#999")+";c.lineWidth=1;c.strokeRect(wL,wT,wW,wH);")
M.append("  c.fillStyle="+q("#666")+";c.font="+q("9px sans-serif")+";c.textAlign="+q("right")+";")
M.append("  c.fillText("+q("1.0")+",wL-3,wT+3);c.fillText("+q("0")+",wL-3,wCY+3);c.fillText("+q("-1.0")+",wL-3,wB+3);")
M.append("  c.textAlign="+q("center")+";")
M.append("  for(i=0;i<=5;i++)c.fillText((i*tMax/5).toFixed(0),tXf(i*tMax/5),wB+13);")
M.append("  c.fillText("+q("t (s)")+",wL+wW/2,H-5);")
M.append("  drawWv(x1v,c1,n);drawWv(x2v,c2,n);")
M.append("  if(n>0&&n<nP){var t=n*tMax/nP;")
M.append("    c.setLineDash([2,2]);c.strokeStyle="+q("#666")+";c.lineWidth=0.5;")
M.append("    c.beginPath();c.moveTo(tXf(t),wT);c.lineTo(tXf(t),wB);c.stroke();c.setLineDash([]);}")
M.append("}")
