import base64, os
DQ = chr(34)
BS = chr(92)
DDQ = DQ+DQ
EM = chr(8212)
NL = chr(10)
def q(s): return DDQ+s+DDQ

L = []
L.append('        /// <summary>')
L.append('        /// Generates a synchronized Canvas animation with mass-spring-damper,')
L.append('        /// phasor spiral, and sinusoidal waveform '+EM+' all driven by requestAnimationFrame.')
L.append('        /// Parameters: xi1, xi2 (damping ratios), label1, label2, title, wn')
L.append('        /// </summary>')
L.append('        private string GenerateSpringAnimation(int w, int h, Dictionary<string, string> p)')
L.append('        {')
L.append('            var title = p.GetValueOrDefault('+DQ+'title'+DQ+', '+DQ+'Animacion Sincronizada'+DQ+');')
L.append('            var xi1 = p.GetValueOrDefault('+DQ+'xi1'+DQ+', p.GetValueOrDefault('+DQ+'xi'+DQ+', '+DQ+'0.125'+DQ+'));')
L.append('            var xi2 = p.GetValueOrDefault('+DQ+'xi2'+DQ+', '+DQ+'0.5'+DQ+');')
L.append('            var label1 = p.GetValueOrDefault('+DQ+'label1'+DQ+', '+DQ+'poco amortiguamiento'+DQ+');')
L.append('            var label2 = p.GetValueOrDefault('+DQ+'label2'+DQ+', '+DQ+'buen amortiguamiento'+DQ+');')
L.append('            var wnVal = p.GetValueOrDefault('+DQ+'wn'+DQ+', '+DQ+'2'+DQ+');')
L.append('')
L.append('            // Unique ID to avoid collisions when multiple animations coexist')
L.append('            var uid = '+DQ+'sa'+DQ+' + Guid.NewGuid().ToString('+DQ+'N'+DQ+').Substring(0, 8);')
L.append('')
L.append('            // Escape strings for safe JS embedding')
jsesc = '            string JsEsc(string s) => s.Replace('+DQ+BS+BS+DQ+', '+DQ+BS+BS+BS+BS+DQ+').Replace('+DQ+BS+DQ+DQ+', '+DQ+BS+BS+BS+DQ+DQ+').Replace('+DQ+BS+'+'"n"'+'+DQ+', '+DQ+' '+DQ+').Replace('+DQ+BS+'+'"r"'+'+DQ+', '+DQ+DQ+');'
L.append(jsesc)
L.append('')
L.append('            var sb = new StringBuilder();')
L.append('')
L.append('            // Canvas element')
L.append('            sb.Append('+DQ+'<canvas id='+BS+DQ+DQ+').Append(uid)')
L.append('              .Append('+DQ+BS+DQ+' width='+BS+DQ+'880'+BS+DQ+' height='+BS+DQ+'480'+BS+DQ+' style='+BS+DQ+'border:2px solid #ddd;border-radius:8px;background:#fafafa;display:block;margin:10px auto'+BS+DQ+'></canvas>'+DQ+');')
L.append('')
L.append('            // Speed slider controls')
L.append('            sb.Append('+DQ+'<div style='+BS+DQ+'text-align:center;margin:6px auto;font-size:12px;color:#555;font-family:sans-serif'+BS+DQ+'>'+DQ+');')
L.append('            sb.Append('+DQ+'<label>&#9654; Velocidad: <input type='+BS+DQ+'range'+BS+DQ+' id='+BS+DQ+DQ+').Append(uid).Append('+DQ+'spd'+BS+DQ+' min='+BS+DQ+'0.1'+BS+DQ+' max='+BS+DQ+'3.0'+BS+DQ+' step='+BS+DQ+'0.1'+BS+DQ+' value='+BS+DQ+'0.6'+BS+DQ+' style='+BS+DQ+'width:200px;vertical-align:middle'+BS+DQ+'> '+DQ+');')
L.append('            sb.Append('+DQ+'<b><span id='+BS+DQ+DQ+').Append(uid).Append('+DQ+'sv'+BS+DQ+'>0.6</span>x</b></label>'+DQ+');')
L.append('            sb.Append('+DQ+'&nbsp;&nbsp;<button id='+BS+DQ+DQ+').Append(uid).Append('+DQ+'rst'+BS+DQ+' style='+BS+DQ+'font-size:11px;padding:2px 8px;cursor:pointer'+BS+DQ+'>Reset</button>'+DQ+');')
L.append('            sb.Append('+DQ+'</div>'+DQ+');')
L.append('')
L.append('            // Build JS '+EM+' ported from sync_anim$ macro (anim_lib.cpd)')
L.append('            var js = @'+DQ+'(function(){')
L.append('var cv=document.getElementById('+q('__UID__')+');if(!cv)return;')
L.append('var c=cv.getContext('+q('2d')+'),W=880,H=480;')
L.append('var wn=__WN__,tMax=25,nP=500,prog=0,spd=0.6,pF=0;')
L.append('var x1v=__XI1__,x2v=__XI2__,c1='+q('#d32f2f')+',c2='+q('#1565c0')+';')
L.append('var sl=document.getElementById('+q('__UID__spd')+'),sv=document.getElementById('+q('__UID__sv')+'),rb=document.getElementById('+q('__UID__rst')+');')
L.append('if(sl){sl.addEventListener('+q('input')+',function(){spd=parseFloat(this.value);sv.textContent=spd.toFixed(1);});}')
L.append('if(rb){rb.addEventListener('+q('click')+',function(){spd=0.6;sl.value=0.6;sv.textContent='+q('0.6')+';prog=0;pF=0;});}')
L.append('var msH=185,eq=115,amp=35,pcx=135,pcy=340,pR=120;')
L.append('var wL=295,wR=865,wT=220,wB=460,wW=wR-wL,wH=wB-wT,wCY=wT+wH/2;')
L.append('function rsp(t,xi){var w=wn*Math.sqrt(1-xi*xi);return Math.exp(-xi*wn*t)*Math.sin(w*t);}')
L.append('function env(t,xi){return Math.exp(-xi*wn*t);}')
L.append('function pXf(t,xi){var w=wn*Math.sqrt(1-xi*xi);return Math.exp(-xi*wn*t)*Math.cos(w*t);}')
L.append('function tXf(t){return wL+(t/tMax)*wW;}')
L.append('function vYf(v){return wCY-v*(wH/2);}')
L.append('function zig(x,y1,y2,n){')
L.append('  var s=(y2-y1)/(2*n+2);c.beginPath();c.moveTo(x,y1);c.lineTo(x,y1+s);')
L.append('  for(var i=0;i<n;i++){c.lineTo(x-10,y1+s*(2*i+2));c.lineTo(x+10,y1+s*(2*i+3));}')
L.append('  c.lineTo(x,y2);c.strokeStyle='+q('#777')+';c.lineWidth=1.5;c.stroke();')
L.append('}')
L.append('function pis(x,y1,y2){')
L.append('  var m=(y1+y2)/2,pw=7,ph=14;c.strokeStyle='+q('#aaa')+';c.lineWidth=1.5;')
L.append('  c.beginPath();c.moveTo(x,y1);c.lineTo(x,m-ph/2);c.stroke();')
L.append('  c.strokeRect(x-pw,m-ph/2,pw*2,ph);')
L.append('  c.beginPath();c.moveTo(x,m+ph/2);c.lineTo(x,y2);c.stroke();')
L.append('}')
L.append('function bx(x,y,w,h,col,txt){')
L.append('  c.fillStyle=col;c.fillRect(x,y,w,h);c.fillStyle='+q('#fff')+';')
L.append('  c.font='+q('bold 13px sans-serif')+';c.textAlign='+q('center')+';c.fillText(txt,x+w/2,y+h/2+5);')
L.append('}')
L.append('function drawMS(tCur){')
L.append('  var a1=amp*rsp(tCur,x1v),a2=amp*rsp(tCur,x2v);')
L.append('  c.fillStyle='+q('#333')+';c.font='+q('bold 12px sans-serif')+';c.textAlign='+q('center')+';')
L.append('  c.fillText('+q('__TITLE__')+',W/2,16);')
L.append('  var px1=290;')
L.append('  c.fillStyle=c1;c.font='+q('bold 10px sans-serif')+';')
L.append('  c.fillText('+DDQ+BS+'u03BE = '+DDQ+'+x1v+'+DDQ+' (__LAB1__)'+DDQ+',px1,33);')
L.append('  c.fillStyle='+q('#666')+';c.fillRect(px1-50,40,100,5);')
L.append('  for(var i=0;i<5;i++)c.fillRect(px1-45+i*20,35,2,5);')
L.append('  zig(px1-18,45,eq+a1,5);pis(px1+18,45,eq+a1);bx(px1-22,eq+a1,44,32,c1,'+q('m')+');')
L.append('  var px2=590;')
L.append('  c.fillStyle=c2;c.font='+q('bold 10px sans-serif')+';')
L.append('  c.fillText('+DDQ+BS+'u03BE = '+DDQ+'+x2v+'+DDQ+' (__LAB2__)'+DDQ+',px2,33);')
L.append('  c.fillStyle='+q('#666')+';c.fillRect(px2-50,40,100,5);')
L.append('  for(var i=0;i<5;i++)c.fillRect(px2-45+i*20,35,2,5);')
L.append('  zig(px2-18,45,eq+a2,5);pis(px2+18,45,eq+a2);bx(px2-22,eq+a2,44,32,c2,'+q('m')+');')
L.append('  c.setLineDash([3,3]);c.strokeStyle='+q('#bbb')+';c.lineWidth=0.5;')
L.append('  c.beginPath();c.moveTo(200,eq+16);c.lineTo(700,eq+16);c.stroke();c.setLineDash([]);')
L.append('  c.fillStyle='+q('#aaa')+';c.font='+q('8px sans-serif')+';c.textAlign='+q('left')+';c.fillText('+q('equilibrio')+',205,eq+14);')
L.append('  if(Math.abs(a1)>2){c.strokeStyle=c1;c.lineWidth=1;')
L.append('    c.beginPath();c.moveTo(px1+28,eq+16);c.lineTo(px1+28,eq+a1+16);c.stroke();')
L.append('    c.beginPath();c.moveTo(px1+25,eq+a1+16);c.lineTo(px1+28,eq+a1+10);c.stroke();')
L.append('    c.beginPath();c.moveTo(px1+31,eq+a1+16);c.lineTo(px1+28,eq+a1+10);c.stroke();}')
L.append('  if(Math.abs(a2)>2){c.strokeStyle=c2;c.lineWidth=1;')
L.append('    c.beginPath();c.moveTo(px2+28,eq+16);c.lineTo(px2+28,eq+a2+16);c.stroke();')
L.append('    c.beginPath();c.moveTo(px2+25,eq+a2+16);c.lineTo(px2+28,eq+a2+10);c.stroke();')
L.append('    c.beginPath();c.moveTo(px2+31,eq+a2+16);c.lineTo(px2+28,eq+a2+10);c.stroke();}')
L.append('  c.textAlign='+q('center')+';c.font='+q('11px sans-serif')+';')
L.append('  c.fillStyle=c1;c.fillText('+DDQ+BS+'u2195 Vibra MUCHO'+DDQ+',px1,msH-5);')
L.append('  c.fillStyle=c2;c.fillText('+DDQ+BS+'u2195 Vibra poco'+DDQ+',px2,msH-5);')
L.append('}')
